-- ============================================================
-- Bem Care – Script DDL Oracle
-- Executar no Oracle FIAP antes de iniciar a aplicação
-- ============================================================

-- Sequências
CREATE SEQUENCE SEQ_BC_DENTISTA    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BC_PACIENTE    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BC_AGENDAMENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BC_USUARIO     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BC_ESPECIALIDADE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BC_CIDADE      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tabela de Dentistas
CREATE TABLE T_BC_DENTISTA (
    ID           NUMBER        PRIMARY KEY,
    NOME         VARCHAR2(100) NOT NULL,
    CRO          VARCHAR2(20)  NOT NULL UNIQUE,
    ESPECIALIDADE VARCHAR2(80),
    EMAIL        VARCHAR2(100),
    CIDADE       VARCHAR2(80)
);

-- Tabela de Pacientes
CREATE TABLE T_BC_PACIENTE (
    ID          NUMBER        PRIMARY KEY,
    NOME        VARCHAR2(100) NOT NULL,
    IDADE       NUMBER(3)     NOT NULL,
    RESPONSAVEL VARCHAR2(100),
    CIDADE      VARCHAR2(80),
    TELEFONE    VARCHAR2(20)
);

-- Tabela de Agendamentos
CREATE TABLE T_BC_AGENDAMENTO (
    ID             NUMBER         PRIMARY KEY,
    NOME_PACIENTE  VARCHAR2(100)  NOT NULL,
    RESPONSAVEL    VARCHAR2(100),
    TELEFONE       VARCHAR2(20)   NOT NULL,
    CIDADE         VARCHAR2(80),
    DATA_PREFERIDA VARCHAR2(20)   NOT NULL,
    PERIODO        VARCHAR2(10)   NOT NULL,
    MOTIVO         VARCHAR2(300),
    STATUS         VARCHAR2(20)   DEFAULT 'Pendente' NOT NULL,
    CRIADO_EM      DATE           DEFAULT SYSDATE
);

-- Tabela de Usuários (login)
CREATE TABLE T_BC_USUARIO (
    ID     NUMBER        PRIMARY KEY,
    EMAIL  VARCHAR2(100) NOT NULL UNIQUE,
    SENHA  VARCHAR2(100) NOT NULL,
    PERFIL VARCHAR2(20)  DEFAULT 'VOLUNTARIO'
);

-- Tabela de Especialidades (tabela auxiliar)
CREATE TABLE T_BC_ESPECIALIDADE (
    ID        NUMBER       PRIMARY KEY,
    DESCRICAO VARCHAR2(80) NOT NULL UNIQUE
);

-- Tabela de Cidades (tabela auxiliar)
CREATE TABLE T_BC_CIDADE (
    ID     NUMBER       PRIMARY KEY,
    NOME   VARCHAR2(80) NOT NULL,
    ESTADO VARCHAR2(2)  NOT NULL
);

-- ============================================================
-- Dados de exemplo
-- ============================================================
INSERT INTO T_BC_ESPECIALIDADE VALUES (SEQ_BC_ESPECIALIDADE.NEXTVAL, 'Ortodontia');
INSERT INTO T_BC_ESPECIALIDADE VALUES (SEQ_BC_ESPECIALIDADE.NEXTVAL, 'Odontopediatria');
INSERT INTO T_BC_ESPECIALIDADE VALUES (SEQ_BC_ESPECIALIDADE.NEXTVAL, 'Clínico Geral');
INSERT INTO T_BC_ESPECIALIDADE VALUES (SEQ_BC_ESPECIALIDADE.NEXTVAL, 'Periodontia');

INSERT INTO T_BC_CIDADE VALUES (SEQ_BC_CIDADE.NEXTVAL, 'São Paulo', 'SP');
INSERT INTO T_BC_CIDADE VALUES (SEQ_BC_CIDADE.NEXTVAL, 'Rio de Janeiro', 'RJ');
INSERT INTO T_BC_CIDADE VALUES (SEQ_BC_CIDADE.NEXTVAL, 'Campinas', 'SP');

INSERT INTO T_BC_DENTISTA VALUES (SEQ_BC_DENTISTA.NEXTVAL, 'Dra. Ana Souza', 'CRO-SP 12345', 'Ortodontia', 'ana@turmadobem.org', 'São Paulo');
INSERT INTO T_BC_DENTISTA VALUES (SEQ_BC_DENTISTA.NEXTVAL, 'Dr. Carlos Lima', 'CRO-RJ 54321', 'Odontopediatria', 'carlos@turmadobem.org', 'Rio de Janeiro');

INSERT INTO T_BC_PACIENTE VALUES (SEQ_BC_PACIENTE.NEXTVAL, 'João Pedro', 12, 'Maria Silva', 'São Paulo', '(11) 99999-0001');
INSERT INTO T_BC_PACIENTE VALUES (SEQ_BC_PACIENTE.NEXTVAL, 'Lucas Almeida', 14, 'Ana Almeida', 'Campinas', '(19) 99999-0002');

COMMIT;
