# -------------------------------------------------------
# Bem Care – Quarkus API
# -------------------------------------------------------

# Porta padrão
quarkus.http.port=8080

# Habilitar CORS para o front-end em desenvolvimento
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=origin,content-type,accept,authorization
